### ISSUE TITLE
Bitbucket PR hook support

### ISSUE THREAD

**Issue by nobre84** [bitrise-io/bitrise-webhooks#6]
Hi! Is this being worked on by bitrise team ? How one could approach implementing this , beside understanding the API at https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html ? Any tips ?

**Comment by viktorbenei** [comment]
Hi,

Unfortunately adding support to that involves other parts of the system. It have to be handled here, on the webhook level (to convert it to Build Trigger parameters - just like you can see it in the GitHub handler), but also have to be handled in the step (Git Clone) as well as in the website backend, to send back the status of the PR, instead of the commit's.

The webhook and step parts are open source, but the API communication between Bitrise.io and Bitbucket.org (to send back the status of the PR) is not.

Don't worry, this task (Bitbucket PR support) is at the top of our task list ;)
