### ISSUE TITLE
Bitbucket Server: handle deleting a branch

### ISSUE THREAD

**Issue by arturdryomov** [bitrise-io/bitrise-webhooks#77]
On deleting a branch Bitbucket Server sends [push event](https://confluence.atlassian.com/bitbucketserver055/event-payload-940682389.html#Eventpayload-repositoryevents) with `type` set to `DELETE`.

Currently Bitrise reacts to it as error.

```json
{
    "error": "Failed to transform the webhook: 'changes' specified in the webhook, but none can be transformed into a build. Collected errors: [Not a type=UPDATE nor type=ADD change. Change.Type was: DELETE]"
}
```

There are two approaches to handle this.

1. Abort running builds for a deleted branch.
2. Change handling to ignore the event without raising an error.

The first one sounds better to me but seems like there is no API to abort the build, at least I haven’t found one in this repository — hooks usually trigger builds and do not abort them.

We can contribute to the project but not sure with the direction we should take. @viktorbenei, can you please assist with this?

**Comment by godrei** [comment]
Hi @ming13 ,

thanks for the report!

What do you mean by:

> Currently Bitrise reacts to it as error.

Does the mentioned payload appear at the webhook's event log page, does it have any other effects?

**Comment by ming13** [comment]
@godrei, yep, the JSON above is taken from Bitbucket Server settings page. It is shown as a `400` response which Bitbucket takes as an error.

**Comment by godrei** [comment]
As far as i see, all of the supported services are returning an error in case of an unsupported webhook. Can not you just disable sending webhook for this event on Bitbucket server?

**Comment by godrei** [comment]
> And actually it is a supported webhook event. 

I meant not supported by Bitrise.

Regarding:

>  does it make sense to implement aborting the build on branch delete events? Is there an API in this project allowing to do that?

Now the webhook-server can only trigger builds on Bitrise, it is not prepared to abort running builds. I will discuss this question with the team.

Skipping the incoming webhook in case of DELETE event may make sense, but i need to discuss it with the team as well, since we do not handle any other events this way. 

My small problem is that i still can not see, what is the issue other than there is an error message on your event log page.

**Comment by ming13** [comment]
Actually there is an issue and it is a pretty serious one. [Bitbucket will skip the webhook if it produced errors too many times](https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html#ManagingwebhooksinBitbucketServer-Circuitbreaking). 

> By default, when a webhook fails five times, it is considered unhealthy and is skipped. Initially, it will only be skipped for a short period (10 seconds) but as it continues to fail it will gradually skip for longer periods, up to a max of 10 hours. 

It actually happened to us when we were working on our own webhook. In such cases Bitbucket produces such a message.

> com.atlassian.webhooks.DispatchFailedException: Webhook failed too many times. Skipping this webhook for the next 36678ms

Because we remove branches quite often Bitrise webhook sits at `259/345 (75%)` success rate according to Bitbucket. I. e. there is a chance that Bitbucket would skip a webhook and build would not be triggered at all.

**Comment by viktorbenei** [comment]
Indeed due to "error rate" Bitbucket and I guess Bitbucket Server can also disable hooks. It's a simple fix in the code to return with an error but with a 200 code, just have to add `ShouldSkip: true` to the `TransformResultModel`, e.g.: https://github.com/bitrise-io/bitrise-webhooks/blob/62a5a0add5785e279944c935eb82b9b2027a7f4e/service/hook/bitbucketserver/bitbucketserver.go#L192
